function ddHddu = ddHddu(R,rho,s,u)
%DDHDDU
%    DDHDDU = DDHDDU(R,RHO,S,U)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:01:00

t2 = rho.*2.0;
t3 = s.*2.0;
t4 = u.*2.0;
ddHddu = reshape([R+t2,0.0,t4,0.0,t2,t3,t4,t3,0.0],[3,3]);
