function dHdu = dHdu(R,lamda2,rho,s,u,u_sat,w_n,w_s)
%DHDU
%    DHDU = DHDU(R,LAMDA2,RHO,S,U,U_SAT,W_N,W_S)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:01:00

dHdu = [R.*u+rho.*u.*2.0+lamda2.*w_n.^2;-w_s+rho.*s.*2.0;s.^2+u.^2-u_sat.^2];
