function dPHIdx = dPHIdx(X1,X2,q_f1,q_f2,ref1,ref2)
%DPHIDX
%    DPHIDX = DPHIDX(X1,X2,Q_F1,Q_F2,REF1,REF2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:01:00

dPHIdx = [q_f1.*(X1-ref1);q_f2.*(X2-ref2)];
