function ddHddu = ddHddu(r1,r2,r3,r4)
%DDHDDU
%    DDHDDU = DDHDDU(R1,R2,R3,R4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:36:33

ddHddu = reshape([r1,0.0,0.0,0.0,0.0,r2,0.0,0.0,0.0,0.0,r3,0.0,0.0,0.0,0.0,r4],[4,4]);
