function dPHIdx = dPHIdx(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,q_f1,q_f2,q_f3,q_f4,q_f5,q_f6,q_f7,q_f8,q_f9,q_f10,q_f11,q_f12,ref1,ref2,ref3,ref4,ref5,ref6,ref7,ref8,ref9,ref10,ref11,ref12)
%DPHIDX
%    DPHIDX = DPHIDX(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,Q_F1,Q_F2,Q_F3,Q_F4,Q_F5,Q_F6,Q_F7,Q_F8,Q_F9,Q_F10,Q_F11,Q_F12,REF1,REF2,REF3,REF4,REF5,REF6,REF7,REF8,REF9,REF10,REF11,REF12)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:36:34

dPHIdx = [q_f1.*(X1-ref1);q_f2.*(X2-ref2);q_f3.*(X3-ref3);q_f4.*(X4-ref4);q_f5.*(X5-ref5);q_f6.*(X6-ref6);q_f7.*(X7-ref7);q_f8.*(X8-ref8);q_f9.*(X9-ref9);q_f10.*(X10-ref10);q_f11.*(X11-ref11);q_f12.*(X12-ref12)];
