function f = statefcn(Jx,Jy,Jz,X2,X4,X6,X7,X8,X9,X10,X11,X12,g,k,l,m,u1,u2,u3,u4)
%STATEFCN
%    F = STATEFCN(JX,JY,JZ,X2,X4,X6,X7,X8,X9,X10,X11,X12,G,K,L,M,U1,U2,U3,U4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 18:36:32

t2 = cos(X9);
t3 = cos(X11);
t4 = sin(X7);
t5 = sin(X9);
t6 = sin(X11);
t7 = 1.0./m;
t8 = -u4;
t9 = u1+u2+u3+u4;
f = [X2;t7.*t9.*(t5.*t6+t2.*t3.*t4);X4;-t7.*t9.*(t3.*t5-t2.*t4.*t6);X6;-g+t2.*t7.*t9.*cos(X7);X8;(l.*(u1-u2))./Jx;X10;(l.*(t8+u3))./Jy;X12;(k.*(t8+u1+u2-u3))./Jz];
