function ddHddu = ddHddu(R1,delta,rho,s)
%DDHDDU
%    DDHDDU = DDHDDU(R1,DELTA,RHO,S)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Jun-2020 17:37:35

t2 = delta.*2.0;
t3 = rho.*2.0;
t4 = s.*2.0;
ddHddu = reshape([R1+t3,0.0,t2,0.0,t3,t4,t2,t4,0.0],[3,3]);
