function dHdu = dHdu(I,K_f,R1,V,delta,delta_max,l_f,lamda4,lamda5,m,rho,s,w_s)
%DHDU
%    DHDU = DHDU(I,K_F,R1,V,DELTA,DELTA_MAX,L_F,LAMDA4,LAMDA5,M,RHO,S,W_S)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Jun-2020 17:37:35

dHdu = [R1.*delta+delta.*rho.*2.0+(K_f.*l_f.*lamda4.*2.0)./I+(K_f.*lamda5.*2.0)./(V.*m);-w_s+rho.*s.*2.0;delta.^2-delta_max.^2+s.^2];
