function dHdx = dHdx(I,K_f,K_r,V,W,beta,l_f,l_r,lamda1,lamda2,lamda3,lamda4,lamda5,m,p,px,py,q_1,q_2,q_3,q_4,q_5,r,radius,ref1,ref2,ref3,ref4,ref5,theta)
%DHDX
%    DHDX = DHDX(I,K_F,K_R,V,W,BETA,L_F,L_R,LAMDA1,LAMDA2,LAMDA3,LAMDA4,LAMDA5,M,P,PX,PY,Q_1,Q_2,Q_3,Q_4,Q_5,R,RADIUS,REF1,REF2,REF3,REF4,REF5,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Jun-2020 17:37:35

t2 = beta+theta;
t3 = px.^2;
t4 = py.^2;
t5 = radius.^2;
t7 = 1.0./I;
t9 = 1.0./V;
t11 = 1.0./m;
t6 = cos(t2);
t8 = sin(t2);
t10 = t9.^2;
t12 = -t5;
t13 = V.*lamda2.*t6;
t14 = V.*lamda1.*t8;
t16 = t3+t4+t12;
t15 = -t14;
t17 = 1.0./t16;
dHdx = [(q_1.*(px.*2.0-ref1.*2.0))./2.0-p.*px.*t17.*2.0;-p.*(py.*t17.*2.0-(py.*2.0)./((W+py).*(W-py)))+(q_2.*(py.*2.0-ref2.*2.0))./2.0;t13+t15-(q_3.*(ref3.*2.0-theta.*2.0))./2.0;lamda3+q_4.*(r-ref4)-lamda4.*t7.*t9.*(K_f.*l_f.^2+K_r.*l_r.^2).*2.0-lamda5.*t10.*t11.*(K_f.*l_f.*2.0-K_r.*l_r.*2.0+m./t10);t13+t15+(q_5.*(beta.*2.0-ref5.*2.0))./2.0-lamda5.*t10.*t11.*(K_f.*V.*2.0+K_r.*V.*2.0)-lamda4.*t7.*t9.*(K_f.*V.*l_f-K_r.*V.*l_r).*2.0];
