function dPHIdx = dPHIdx(beta,px,py,q_f1,q_f2,q_f3,q_f4,q_f5,r,ref1,ref2,ref3,ref4,ref5,theta)
%DPHIDX
%    DPHIDX = DPHIDX(BETA,PX,PY,Q_F1,Q_F2,Q_F3,Q_F4,Q_F5,R,REF1,REF2,REF3,REF4,REF5,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Jun-2020 17:37:36

dPHIdx = [q_f1.*(px-ref1);q_f2.*(py-ref2);-q_f3.*(ref3-theta);q_f4.*(r-ref4);q_f5.*(beta-ref5)];
